site_name: The Annotated ElectionGuard
# site_description:
site_author: rc-ms
# google_analytics:
# remote_branch: for gh-deploy to GithubPages
# remote_name: for gh-deploy to Github Pages
copyright: "Â©2021 rc-ms"
docs_dir: "docs"
repo_url: https://github.com/rc-ms/the-annotated-eg
nav:
  - About: index.md
  - Use Cases:
    - Precinct Scan: how-to/Precinct_scan.md
  #  - Electionic Ballot Delivery: how-to/Electronic_ballot_delivery.md
  #  - Mobile Voting: how-to/Mobile_voting.md
  #- Processes:
  #  - Key Ceremony: processes/Key_ceremony.md
  # - Tally Ceremony: processes/Tally_ceremony.md
  # - Verifying an Election: processes/Verifier.md
  #  - Publishing an Election Result: processes/Publishing.md
  #- Modules:
  #  - Specification: modules/Specification.md
  #  - Python Full Service Module: modules/Python.md
  #  - C++ Encryption Module: modules/Cpp.md
  - Content creation:
      - Daily notes: features/daily-notes.md
      - Graph visualization: features/graph-visualization.md
      - Link reference definitions: features/link-reference-definitions.md
      - Note properties: features/note-properties.md
      - Note templates: features/note-templates.md
      - Spell checking: features/spell-checking.md
      - Tags and tag explorer: features/tags-and-tag-explorer.md
      - Wiki links: features/wiki-links.md
      - Keyboard shortcuts for editing: features/use-keyboard-shortcuts-for-editing.md
      - Write notes in foam: features/write-notes-in-foam.md
      - Paste images from clipboard: features/paste-images-from-clipboard.md
plugins:
  - search
theme:
  name: material
  custom_dir: overrides
  favicon: images/favicon.ico
  logo: images/electionguard-logo.png
  font:
    text: Segoe UI
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.instant
markdown_extensions:
  - admonition
  - footnotes
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js